In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import torchvision
from torchvision import datasets, transforms

In [11]:
inp = torch.randn(3,1, 4, 4)
conv1 = nn.Conv2d(1, 5, 3, 1)
conv2 = nn.ConvTranspose2d(5, 7, 3, stride=2)
out = conv1(inp)
out2 = conv2(out)
print(out2.size())

torch.Size([3, 7, 5, 5])


In [37]:
a = torch.arange(9)
b = torch.arange(9)
c = torch.dot(a,b)
print(a)
print(b)
d = b * a
print(c)
print(d)
e = torch.arange(9).reshape(9,1)
f = e * a
print(e)
print(f)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])
tensor(204)
tensor([ 0,  1,  4,  9, 16, 25, 36, 49, 64])
tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8]])
tensor([[ 0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 0,  2,  4,  6,  8, 10, 12, 14, 16],
        [ 0,  3,  6,  9, 12, 15, 18, 21, 24],
        [ 0,  4,  8, 12, 16, 20, 24, 28, 32],
        [ 0,  5, 10, 15, 20, 25, 30, 35, 40],
        [ 0,  6, 12, 18, 24, 30, 36, 42, 48],
        [ 0,  7, 14, 21, 28, 35, 42, 49, 56],
        [ 0,  8, 16, 24, 32, 40, 48, 56, 64]])
